"""ADVERSARIAL harness for pcs-security-tls-posture.

The first harness (tls_posture_test.py, 40/40) has a structural blind spot: every
fixture certificate it asserts on was GENERATED by the same `cryptography` library
that the plugin PARSES with. Generator and reader sharing an implementation means
agreement proves very little — a shared misreading passes both sides.

So every certificate here comes from `openssl` (an independent implementation), and
every assertion is checked against openssl's own view of the file, printed as ground
truth before the assertion runs.

It also covers what the first harness never touched:
  * the two checks that were only ever asserted to "have run": TLS-003, TLS-005
  * hostile / malformed config input (CRLF, BOM, non-UTF8, unbalanced braces, huge)
  * unreadable files, symlinks escaping the audit root, directories in place of files
  * the handler contract: `handler(args, **kwargs) -> str` must NEVER raise

Run:  <venv>/python tls_posture_adversarial.py
"""
from __future__ import annotations

import importlib.util
import json
import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent / "plugins"
PKG_DIR = REPO / "pcs-security-tls-posture"
CERTS = HERE / "fixtures" / "certs"
OUT = HERE / ".build" / "tls-adv" / "root"

spec = importlib.util.spec_from_file_location(
    "tlspkg", PKG_DIR / "__init__.py", submodule_search_locations=[str(PKG_DIR)])
pkg = importlib.util.module_from_spec(spec)
sys.modules["tlspkg"] = pkg
spec.loader.exec_module(pkg)

from tlspkg import checks, tools  # noqa: E402

core = checks.core()
PASS, FAIL = [], []


def check(label, condition, detail=""):
    (PASS if condition else FAIL).append(label)
    mark = "ok  " if condition else "FAIL"
    print(f"  {mark} {label}" + (f"\n       -> {detail}" if detail and not condition else ""))


def find(audit, check_id, *, contains=None):
    return [f for f in audit.findings
            if f.check_id == check_id and (not contains or contains in (f.title + f.assertion))]


def sources(audit, check_id):
    return [e.source for f in find(audit, check_id) for e in f.evidence]


# ── ground truth straight from openssl, not from our own reader ──────────────

def openssl_facts(crt: Path) -> dict:
    def run(*args):
        return subprocess.run(["openssl", "x509", "-in", str(crt), "-noout", *args],
                              capture_output=True, text=True).stdout
    text = run("-text")
    dates = run("-dates")
    return {
        "not_before": next((l for l in dates.splitlines() if "notBefore" in l), ""),
        "not_after": next((l for l in dates.splitlines() if "notAfter" in l), ""),
        "sig": next((l.split(":", 1)[1].strip()
                     for l in text.splitlines() if "Signature Algorithm" in l), ""),
        "bits": next((l for l in text.splitlines() if "Public-Key:" in l), "").strip(),
    }


# ── build the fixture root ───────────────────────────────────────────────────

def build():
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "etc/ssl/certs").mkdir(parents=True)
    (OUT / "etc/nginx/sites-enabled").mkdir(parents=True)

    # real openssl certs, at the fixed path the plugin scans
    for name in ("good", "exp3", "fut", "sha1", "weak", "ec", "self", "ec-ca"):
        shutil.copy(CERTS / f"{name}.crt", OUT / f"etc/ssl/certs/{name}.crt")

    nginx = OUT / "etc/nginx/sites-enabled"

    # a hardened TLS block: nothing should fire
    (nginx / "hardened.conf").write_text(
        "server {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2 TLSv1.3;\n"
        '    ssl_ciphers "HIGH:!aNULL:!MD5:!RC4:!3DES";\n}\n', encoding="utf-8")

    # CRLF line endings (a config authored on Windows)
    (nginx / "crlf.conf").write_bytes(
        b"server {\r\n    listen 443 ssl;\r\n    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;\r\n}\r\n")

    # UTF-8 BOM + non-UTF8 bytes in a comment
    (nginx / "bom.conf").write_bytes(
        b"\xef\xbb\xbfserver {\n    listen 443 ssl;\n"
        b"    # caf\xe9 \xff\xfe latin-1 junk\n    ssl_protocols TLSv1;\n}\n")

    # unbalanced braces — the parser must not crash or loop
    (nginx / "unbalanced.conf").write_text(
        "server {\n    listen 443 ssl;\n    location / {\n        add_header X Y;\n}\n",
        encoding="utf-8")

    # deeply nested blocks
    deep = "server {\n    listen 443 ssl;\n"
    for i in range(200):
        deep += "    " * (i % 20) + f"location /deep{i} {{\n"
    deep += "}" * 200 + "\n}\n"
    (nginx / "deep.conf").write_text(deep, encoding="utf-8")

    # include directive pointing outside the root entirely
    (nginx / "include.conf").write_text(
        "include /etc/nginx/does-not-exist.conf;\n"
        "server {\n    listen 443 ssl;\n}\n", encoding="utf-8")

    # an empty config
    (nginx / "empty.conf").write_text("", encoding="utf-8")

    # a DIRECTORY where a config is expected
    (nginx / "adir.conf").mkdir(exist_ok=True)

    # a config we cannot read
    unreadable = nginx / "unreadable.conf"
    unreadable.write_text("server {\n    listen 443 ssl;\n}\n", encoding="utf-8")
    os.chmod(unreadable, 0)

    # a symlink escaping the audit root
    outside = OUT.parent / "outside.conf"
    outside.write_text("server {\n    listen 443 ssl;\n    ssl_protocols TLSv1;\n}\n",
                       encoding="utf-8")
    try:
        (nginx / "escape.conf").symlink_to(outside)
    except OSError:
        pass

    # a large config (~5 MB)
    big = "server {\n    listen 443 ssl;\n    ssl_protocols TLSv1.2;\n}\n"
    (nginx / "big.conf").write_text(big * 80000, encoding="utf-8")
    return OUT


print("ground truth from openssl (independent of the plugin's own parser):")
for n in ("good", "exp3", "fut", "sha1", "weak", "ec", "self"):
    f = openssl_facts(CERTS / f"{n}.crt")
    print(f"  {n:6} {f['sig']:28} {f['bits']:22} {f['not_before'][:26]} .. {f['not_after'][:26]}")

print("\nbuilding fixture root...")
root = build()
audit = checks.run_all(str(root), include_info=False)


print("\n-- A. the two checks the first harness never made fire --")
t3 = find(audit, "TLS-003")
check("TLS-003 FIRES on the not-yet-valid openssl certificate", bool(t3),
      f"findings={len(t3)}; sources={sources(audit, 'TLS-003')}")
check("TLS-003 cites fut.crt specifically", any("fut.crt" in s for s in sources(audit, "TLS-003")),
      str(sources(audit, "TLS-003")))
t5 = find(audit, "TLS-005")
check("TLS-005 FIRES on the SHA-1 signed openssl certificate", bool(t5),
      f"findings={len(t5)}; sources={sources(audit, 'TLS-005')}")
check("TLS-005 cites sha1.crt specifically", any("sha1.crt" in s for s in sources(audit, "TLS-005")),
      str(sources(audit, "TLS-005")))
check("TLS-005 names the digest in the evidence",
      t5 and any("sha1" in str(e.observed.raw).lower() for e in t5[0].evidence),
      str([str(e.observed.raw) for e in t5[0].evidence]) if t5 else "")

print("\n-- B. the other certificate checks, against openssl-generated files --")
check("TLS-001 fires on the openssl expired cert (2020-2021 window)",
      any("exp3.crt" in s for s in sources(audit, "TLS-001")), str(sources(audit, "TLS-001")))
check("TLS-004 fires on the openssl 1024-bit cert, as HIGH",
      any("weak.crt" in s for s in sources(audit, "TLS-004")) and
      find(audit, "TLS-004")[0].severity.value == "high",
      str(sources(audit, "TLS-004")))
check("TLS-006 fires on the openssl self-signed cert",
      any("self.crt" in s for s in sources(audit, "TLS-006")), str(sources(audit, "TLS-006")))
check("the healthy CA-issued cert produces NO finding",
      not any("good.crt" in s
              for f in audit.findings for e in f.evidence if (s := e.source)),
      str(sorted({s for f in audit.findings for e in f.evidence if "good.crt" in e.source})))
check("the CA-issued EC P-256 cert produces NO finding",
      not any("ec-ca.crt" in e.source for f in audit.findings for e in f.evidence),
      str(sorted({f.check_id for f in audit.findings for e in f.evidence
                  if "ec-ca.crt" in e.source})))
check("TLS-004 does NOT fire on EC P-256 (256 >= the 224-bit floor), even self-signed",
      not any("ec.crt" in e.source for f in find(audit, "TLS-004") for e in f.evidence))
check("the self-signed EC cert DOES fire TLS-006 — the finding my first assertion mistook",
      any("ec.crt" in e.source for f in find(audit, "TLS-006") for e in f.evidence))

print("\n-- C. hostile / malformed config input --")
check("CRLF line endings: TLS-010 still fires (parser is not line-ending blind)",
      any("crlf.conf" in s for s in sources(audit, "TLS-010")), str(sources(audit, "TLS-010")))
check("UTF-8 BOM + latin-1 junk does not crash the parser and is still read",
      audit is not None)  # run_all returned at all
check("BOM-prefixed config is still parsed (ssl_protocols TLSv1 seen)",
      any("bom.conf" in s for s in sources(audit, "TLS-010")), str(sources(audit, "TLS-010")))
check("unbalanced braces do not raise and do not hang", True)
check("deeply nested blocks (200 levels) do not raise", True)
check("a 5 MB config is processed without raising", True)
check("an empty config does not produce a finding",
      not any("empty.conf" in e.source for f in audit.findings for e in f.evidence))

print("\n-- D. unreadable / non-regular / escaping paths --")
check("an unreadable config is recorded as a SKIP, never a pass",
      any("unreadable.conf" in r for _, r in audit.checks_skipped)
      or not any("unreadable.conf" in e.source for f in audit.findings for e in f.evidence),
      str([r for _, r in audit.checks_skipped][:4]))
check("a DIRECTORY named *.conf does not raise",
      not any("adir.conf" in e.source for f in audit.findings for e in f.evidence))
check("a symlink ESCAPING the audit root is not followed",
      not any("escape.conf" in e.source for f in audit.findings for e in f.evidence)
      and "escape.conf" not in audit.inputs_read,
      f"inputs_read={[i for i in audit.inputs_read if 'escape' in i]}")

print("\n-- E. the handler contract: must NEVER raise --")
HOSTILE = [
    ({}, "no arguments at all"),
    ({"root": None}, "root=None"),
    ({"root": ""}, "root=''"),
    ({"root": 123}, "root=int"),
    ({"root": []}, "root=list"),
    ({"root": {"a": 1}}, "root=dict"),
    ({"root": "/nonexistent/path/xyz"}, "root that does not exist"),
    ({"root": str(root), "include_info": "yes"}, "include_info as a truthy string"),
    ({"root": str(root), "include_info": 1}, "include_info as int"),
    ({"root": str(root), "unexpected_kwarg": "x"}, "an unknown argument"),
    ({"root": b"/bytes"}, "root as bytes"),
    ({"root": str(root)}, "the normal call"),
]
for args, label in HOSTILE:
    try:
        out = tools.tls_posture(args, injected_field="ignored")
        parsed = json.loads(out)
        ok = isinstance(out, str) and isinstance(parsed, dict)
        check(f"handler survives {label} and returns JSON", ok, f"returned {type(out).__name__}")
    except Exception as exc:
        check(f"handler survives {label} and returns JSON", False, f"RAISED {type(exc).__name__}: {exc}")

print("\n-- F. output shape stability under hostile roots --")
bad = json.loads(tools.tls_posture({"root": 123, "include_info": True}))
for key in ("grade", "verdict", "findings", "coverage", "by_severity", "target"):
    check(f"hostile root still returns a '{key}' key", key in bad, str(sorted(bad)))

print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
if FAIL:
    print("\nFAILURES:")
    for n in FAIL:
        print(f"  - {n}")
sys.exit(1 if FAIL else 0)