#!/bin/bash
# Generate the TLS certificate fixtures used by the tls-posture harnesses.
#
# Fixtures are generated, never hand-written, and generated by OPENSSL — not by the Python
# `cryptography` package. The harnesses assert against what this produces, so a fixture that
# was quietly produced by a library the plugin could also use would weaken the evidence.
#
# Validity windows are relative to NOW, not to the day someone committed a PEM file. A
# committed "expires in 30 days" certificate is a test that passes this month and fails
# later; the only certificates pinned to fixed dates are the two that must be permanently
# expired or permanently future-dated.
#
# Run:  bash tests/fixtures/make_certs.sh [outdir]
# Idempotent: it rewrites everything each time.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="${1:-$HERE/certs}"
mkdir -p "$OUT"
cd "$OUT"
rm -f ./*.crt ./*.key ./*.csr ./*.srl

command -v openssl >/dev/null 2>&1 || {
    echo "make_certs.sh: openssl is required to generate the fixtures" >&2
    exit 1
}

say() { printf '  %-10s %s\n' "$1" "$2"; }

# --- RSA roots and leaves ----------------------------------------------------
openssl req -x509 -newkey rsa:2048 -nodes -keyout ca.key -out ca.crt \
    -days 3650 -subj "/CN=TLS Test Root CA" \
    -addext "basicConstraints=critical,CA:TRUE" 2>/dev/null
say "ca.crt" "RSA 2048 self-signed CA, 10 years"

openssl req -newkey rsa:2048 -nodes -keyout good.key -out good.csr \
    -subj "/CN=good.example" 2>/dev/null
openssl x509 -req -in good.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -days 365 -copy_extensions none \
    -extfile <(printf "subjectAltName=DNS:good.example\nbasicConstraints=CA:FALSE") \
    -out good.crt 2>/dev/null
say "good.crt" "RSA 2048, CA-issued, 1 year — the clean control"

openssl req -x509 -newkey rsa:2048 -nodes -keyout self.key -out self.crt \
    -days 365 -subj "/CN=self.example" 2>/dev/null
say "self.crt" "RSA 2048, self-signed"

openssl req -x509 -newkey rsa:2048 -nodes -keyout sha1.key -out sha1.crt \
    -days 365 -sha1 -subj "/CN=sha1.example" 2>/dev/null
say "sha1.crt" "RSA 2048, SHA-1 signed"

# 1024-bit is what makes this "weak"; openssl 3.x still issues it, quietly.
openssl req -x509 -newkey rsa:1024 -nodes -keyout weak.key -out weak.crt \
    -days 365 -subj "/CN=weak.example" 2>/dev/null
say "weak.crt" "RSA 1024, self-signed"

# --- permanently dated: expired and not-yet-valid ----------------------------
# Fixed dates, deliberately: these two must stay expired and un-issued forever, so they
# cannot be generated relative to today.
openssl req -x509 -newkey rsa:2048 -nodes -keyout exp3.key -out exp3.crt \
    -subj "/CN=expired-2020.example" \
    -not_before 20200101000000Z -not_after 20210101000000Z 2>/dev/null
say "exp3.crt" "RSA 2048, expired 2020-2021 (fixed)"

openssl req -x509 -newkey rsa:2048 -nodes -keyout fut.key -out fut.crt \
    -subj "/CN=future.example" \
    -not_before 20300101000000Z -not_after 20310101000000Z 2>/dev/null
say "fut.crt" "RSA 2048, not valid until 2030 (fixed)"

# --- EC ---------------------------------------------------------------------
# The fixture NAMES are counter-intuitive and must stay that way, because the harness
# asserts against them by name:
#   ec.crt      is the SELF-SIGNED EC cert      -> must fire TLS-006
#   ec-ca.crt   is the "CA-issued" EC leaf      -> must produce NO finding
# Read `ca` as "CA-issued", not "certificate authority". An earlier self-signed EC
# fixture made TLS-006 fire where the harness expected silence, and the harness read
# that as a plugin bug when the fixture was the thing that was wrong.
openssl ecparam -name prime256v1 -genkey -noout -out ec.key 2>/dev/null
openssl req -x509 -new -key ec.key -out ec.crt \
    -days 365 -subj "/CN=ec.example" \
    -addext "basicConstraints=critical,CA:TRUE" 2>/dev/null
say "ec.crt" "EC P-256, SELF-SIGNED (fires TLS-006)"

# A separate EC root, only to sign the CA-issued EC leaf below. Not copied by the
# harness, so it can live here under a name that says what it is.
openssl ecparam -name prime256v1 -genkey -noout -out ec-root.key 2>/dev/null
openssl req -x509 -new -key ec-root.key -out ec-root.crt \
    -days 3650 -subj "/CN=Adv Test CA" \
    -addext "basicConstraints=critical,CA:TRUE" 2>/dev/null
openssl ecparam -name prime256v1 -genkey -noout -out ec-ca-key.key 2>/dev/null
openssl req -new -key ec-ca-key.key -out ec-ca.csr \
    -subj "/CN=ec-ca-issued.example" 2>/dev/null
openssl x509 -req -in ec-ca.csr -CA ec-root.crt -CAkey ec-root.key -CAcreateserial \
    -days 365 -copy_extensions none \
    -extfile <(printf "subjectAltName=DNS:ec-ca-issued.example\nbasicConstraints=CA:FALSE") \
    -out ec-ca.crt 2>/dev/null
say "ec-ca.crt" "EC P-256, CA-ISSUED leaf (produces no finding)"

echo
echo "wrote $(ls ./*.crt | wc -l | tr -d ' ') certificates to $OUT"